### ISSUE TITLE
Breaks on Firefox 79

### ISSUE THREAD

**Issue by hbarcelos** [ungap/promise-any#2]
Here's a sample code snippet:

```js
import any from '@ungap/promise-any';

(async() => {
   await Promise.any([
     Promise.resolve(1),
     Promise.reject(new Error('boom')),
   ]);
})
```

If I run the above in Firefox 79 I get the following error:

> Receiver of Promise.any call is not a non-null object

I am not sure why, but looks like `Promise` static methods must be bound to the `Promise` object. I currently have a workaround for this:

```js
import anyPolyfill from '@ungap/promise-any';

const any = typeof Promise.any === 'function' ? Promise.any.bind(Promise) : anyPolyfill;
```

**Comment by WebReflection** [comment]
You are right. Fixed, thanks 👍
